config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :clients do
    resources :problem_user
  end

  get '/' => 'home#index' # Метод вызывает открытия главную страницу без папок
  get '/contact' => 'pages#contact'  # Метод открывает контакты и адрес автосервиса из папки static_pages
  get 'home/index'



  # resource это такой метод который делает маршрут по Path (патерну) Рест (REST) и в Патерне Рест так определено
  # что НЬЮ получает GET  Крейт получает POST
  get 'contacts' => 'contacts#new' # Можно заменить на resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resource :contacts, only: [:create]
  resources :articles do
    resources :comments
  end
  # а дальше идет хешь,  ONLY это ключ хеша, а значение этого Хеша Массив С символами :new, :create методов
  # которые хотим использовать :new, :create
  get 'search' => 'clients#search'
  get 'clients' => 'clients#index' # Методо возвращает форму заполнения после ее ввода

  resources :clients
  resources :clients do
    resources :models
  end

  get 'articles' => 'articles#new'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

 get 'brands' => 'brands#index'
  resources :brands do
    resources :models
  end
  resources :brands

end

app/models/article.rb
class Article < ApplicationRecord

  has_many :comments
  validates :title, presence: true
  validates :text, presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article  #  если использовать Редирект - то  вывод представления из create  отображатьсяя не будет
      # будет делаться редирект на роутер SHOW - файл Креате можно удалить с редиректом он не используется
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id]) # Для того что бы отредактировать , нужно получить Сущьность (переменная обьект)
    # И передать ей все ее свойства, только после этого сущьность можно изменить. Представление edit.html.erb
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article  #  если использовать Редирект - то  вывод представления из create  отображатьсяя не будет
      # будет делаться редирект на роутер SHOW - файл Креате можно удалить с редиректом он не используется
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  # все что ниже Приватного метода не имеет доступа из вне.
  # Далее идет разрешение доступа к запретным атрибутам емайл и контакт
  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Редактирование статьи</h1>

<!- обязательно добaвлять  data: { turbo: false } - так как изменились Релься, -->
<!- иначе не будет отображаться результат на странице -->

  <%= form_for :article, data: { turbo: false }, url: article_path(@article), method: :put do |f| %>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit 'Send message' %>
  </p>

<% end %>

app/views/articles/index.html.erb
<h2>Список статей</h2>
<body>

  <% @articles.each do |article| %>

  <table class="table table-bordered border-primary">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Автор</th>
      <th scope="col">Название статьи</th>
    </tr>
    </thead>

    <tbody class="table-group-divider" class="align-top">
    <tr>
      <th scope="row">1</th>
      <td><p><%= article.title %></p></td>
      <td><p><%= article.text %></p></td>
    </tr>
  </table>

      <p>
        <%= link_to  "Показать статью", article_path(article) %> |
        <%= link_to  "Редактировать статью", edit_article_path(article) %> |
        <%= button_to "Удалить", article_path(article), method: :delete, data: { confirm: 'Действительно удалить?'} %>
      </p>
  <% end %>
</body>







app/views/articles/new.html.erb
<h1>Новая статья</h1>

<!- обязательно добaвлять  data: { turbo: false } - так как изменились Релься, -->
<!- иначе не будет отображаться результат на странице -->

<%= form_for :article, data: { turbo: false }, url: articles_path do |f| %>

  <!-  # вывод сообщения об ошибке -->
  <% if @article && @article.errors.any? %>
    <p>
    <ul>
      <%= @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </p>
  <% end %>

  <p>
    <%= f.label :Автор %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :Название %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit 'Send message' %>
  </p>

<% end %>

app/views/articles/show.html.erb
<h3>Страница вывода текста статьи и автора</h3>
<body class="Secondary" >

<h2>
  <p class="text-success" ><%= @article.title %></p>
</h2>
  <p class="text-dark"><%= @article.text %></p>

<h2>Комментарии</h2>

<% @article.comments.each do |comment| %>
<p>
  <i><%= comment.author %></i><br />
  <%= comment.body %>
</p>
<% end %>

<h2>Добавить Комментарий</h2>
<p>
  <%= form_for([@article, @article.comments.build]) do |f| %>

  <p class="text-success" ><%= f.label :author %><br />
  <p class="text-success" ><%= f.text_field :author %><br />
</p>

  <p class="text-success" ><%= f.label :body %><br />
  <p class="text-success" ><%= f.text_field :body %><br />
  </p>

  <p>
    <%= f.submit %>
  </p>
</body>

<!- обязательно добaвлять  data: { turbo: false } - так как изменились Релься, -->
<!- иначе не будет отображаться результат на странице -->
<% end %>