config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :clients do
    resources :problem_user
  end

  get '/' => 'home#index' # Метод вызывает открытия главную страницу без папок
  get '/contact' => 'pages#contact'  # Метод открывает контакты и адрес автосервиса из папки static_pages
  get 'home/index'



  # resource это такой метод который делает маршрут по Path (патерну) Рест (REST) и в Патерне Рест так определено
  # что НЬЮ получает GET  Крейт получает POST
  get 'contacts' => 'contacts#new' # Можно заменить на resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resource :contacts, only: [:create]
  resources :articles do
    resources :comments
  end
  # а дальше идет хешь,  ONLY это ключ хеша, а значение этого Хеша Массив С символами :new, :create методов
  # которые хотим использовать :new, :create
  get 'search' => 'clients#search'
  get 'clients' => 'clients#index' # Методо возвращает форму заполнения после ее ввода

  resources :clients
  resources :clients do
    resources :models
  end

  get 'articles' => 'articles#new'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

 get 'brands' => 'brands#index'
  resources :brands do
    resources :models
  end
  resources :brands

end

app/models/client.rb
class Client < ApplicationRecord

        validates :number_auto, presence: true
        validates :brand_auto, presence: true
        validates :model_auto, presence: true
        validates :km, presence: true

        has_many :problem_users

        accepts_nested_attributes_for :problem_users

end


app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def new
    @client = Client.new
  end

  def index
    #  Поиск клиента только по номеру авто с чистой таблицы
    # @clients = Client.where(number_auto: params[:search])

    #  вывод Поиск клиента и таблицы всех клиентов
      
     @clients = Client.where(["number_auto LIKE ?", "%#{params[:search]}%"]).order(created_at: :desc)
     
  end

  def show
    @client = Client.find(params[:id])
  end

  def search
  end

  def create

    #  @obj1 = Model1.new model1_params 
    #  @obj1.save 
    #  @obj2 = Model2.new
    #  model2_params 
    #  @obj2.save  #Проверить

    @client = Client.new(client_params)
    @params = params[:problem_user_attributes]
    if @client.valid?
      @client.save
      response = FileUtils.mkdir_p "D:/BAZA/#{client_params[:brand_auto]}/#{client_params[:model_auto]}/#{client_params[:number_auto]}"

      database_file = File.new('D:/BAZA/database.txt', 'a+')
      database_file.puts "#{client_params[:number_auto]}  #{client_params[:brand_auto]}  #{client_params[:model_auto]}  #{client_params[:km]}км.  Сумма #{client_params[:price]} Телефон #{client_params[:phone]} Дата #{client_params[:data]}"
      database_file.close

      id_client = File.new("D:/BAZA/#{client_params[:brand_auto]}/#{client_params[:model_auto]}/#{client_params[:number_auto]}/#{client_params[:number_auto]}.html", 'a+')
      id_client.puts "<body>#{client_params[:number_auto]} #{client_params[:brand_auto]} #{client_params[:model_auto]} #{client_params[:km]}км. Тип ЭБУ #{client_params[:swid]}: Сумма #{client_params[:price]} Телефон #{client_params[:phone]} Дата #{client_params[:data]}<br />#{client_params[:problem_user]}<br />#{client_params[:repair_user]}<br /><body>"
      id_client.close

      redirect_to @client

        else
          render action: 'new'
    end
  end

  def edit
    @client = Client.find(params[:id]) # Для того что бы отредактировать , нужно получить Сущьность (переменная обьект)
    # И передать ей все ее свойства, только после этого сущьность можно изменить. Представление edit.html.erb
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client  #  если использовать Редирект - то  вывод представления из create  отображатьсяя не будет
      # будет делаться редирект на роутер SHOW - файл Креате можно удалить с редиректом он не используется
    else
      render action: 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    redirect_to clients_path
  end

  private

  def client_params
    params.require(:client).permit(:number_auto, :brand_auto, :model_auto, :km, :vin, :problem_user, :repair_user, :swid, :phone, :price, :desc, :data, problem_user_attributes: [:each, :problem_user, :attribute])
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<h1>Редактирование клиентов</h1>

<!- обязательно добaвлять  data: { turbo: false } - так как изменились Релься, -->
<!- иначе не будет отображаться результат на странице -->

  <%= form_for :client, data: { turbo: false }, url: client_path(@client), method: :put do |f| %>


  <div class="hstack gap-3" style="height: 100px;">

    <div class="bg-light border ms-5"><%= f.label :number_auto, 'Гос Номер а/м' %><br><%= f.text_field :number_auto %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :brand_auto, 'Бренд а/м' %><br><%= f.select :brand_auto, ["AUDI", "ACURA", "BMW", "BYD", "CHEVROLET", "CHERY", "CITROEN", "CHANGAN", "CHRYSLER", "DAEWOO", "DODGE", "DAIHATSU", "DATSUN", "DONGFENG", "FORD", "FIAT", "FAW", "FOTON", "INFINITI", "ISUZU", "JAC", "GEELY", "GENESIS", "GREATWALL", "GAC", "HAVAL", "HONDA", "HYUNDAI", "HAIMA", "KIA", "LEXUS", "LIFAN", "MAZDA", "MINI", "MITSUBISHI", "MERCEDESBENZ",  "NISSAN", "OPEL", "PEUGEOT", "RAVON", "RENAULT", "ROVER", "SEAT", "SKODA",  "SSANGYONG", "SUZUKI", "SUBARU", "SMART", "TOYOTA", "VOLKSWAGEN", "VOLVO", "UAZ", "VAZ", "ZAZ", "GAZ"] %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :model_auto, 'Модель а/м' %><br><%= f.text_field :model_auto %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :km, 'Пробег в км' %><br><%= f.text_field :km %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :vin, 'Вин номер' %><br><%= f.text_field :vin %></div>

  </div>

  <div class="hstack gap-3">

    <div class="bg-light border ms-5"><%= f.label :problem_user, 'Жалобы клиента на работу а/м, результат диагностики'%><br><%= f.text_area :problem_user, size: "52x10" %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :repair_user, 'Проделанная работа и пр.' %><br><%= f.text_area :repair_user, size: "52x10" %></div>

  </div>

  <div class="hstack gap-3" style="height: 100px;">

    <div class="bg-light border ms-5"><%= f.label :swid, 'Тип блока, номер софта' %><br><%= f.text_field :swid %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :phone, 'Номер телефона' %><br><%= f.text_field :phone %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :price, 'Стоимость работ' %><br><%= f.text_field :price %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :data, 'Дата и время'%><%= f.datetime_local_field :data %></div>

  </div>

  <div class="hstack gap-3" style="height: 100px;">

    <div class="bg-info ms-5 col-form-label-md"><%= f.label :submit, 'Записать' %><%= f.submit %></div>

    <%= link_to 'Показать все записи а/м', clients_path %>

  </div>

<% end %>

app/views/clients/index.html.erb
<h3>таблица Списка клиентов</h3>

<div class="position-fixed position-absolute srart-50 end-0 translate-middle-y" style="max-width: 540px;">
<%= form_tag clients_path, :method => 'get' do %>
  <div class="text-dark bg-warning">
    <p> Введите номер автомобиля для поиска</p>
  </div>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Поиск" %>
  <% end %><br />
</div>

  <% @clients.each_with_index do |client, index| %>
      <thead>
        <table class="table table-bordered border-primary">
          <tr>
            <th scope="col">№</th>
            <th scope="col">Гос Номе а/м</th>
            <th scope="col">Бренд а/м</th>
            <th scope="col">Модель а/м</th>
            <th scope="col">Пробег в км</th>
            <th scope="col">Тип эбу версия софта</th>
            <th scope="col">Жалоба клиента</th>
          </tr>
      </thead>

          <tbody class="table-group-divider" class="align-top">
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td><p class="text-danger"><%= client.number_auto %></p></td>
              <td><p class="text-success"><%= client.brand_auto %></p></td>
              <td><p class="text-success"><%= client.model_auto %></p></td>
              <td><p class="text-success"><%= client.km %></p></td>
              <td><p class="text-success"><%= client.swid %></p></td>
              <td><p class="text-success"><%= client.problem_user %></p></td>
            </tr>
        </table>

      <p>
        <%= link_to  "Показать клиента", client_path(client) %> |
        <%= link_to  "Редактировать данные клиента", edit_client_path(client) %> |
        <%= button_to "Удалить запись клиента", client_path(client), method: :delete, data: { confirm: 'Действительно удалить?'} %>
      </p>

  <% end %>








app/views/clients/new.html.erb
<%= form_for :client, data: { turbo: false }, url: clients_path do |f| %>

  <!-  # вывод сообщения об ошибке -->
  <% if @client && @client.errors.any? %>
    <p>
    <ul>
      <%= @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </p>
  <% end %>

  <div class="hstack gap-3" style="height: 100px;">

    <div class="bg-light border text-center ms-5"><%= f.label :number_auto, 'Гос Номер а/м' %><br><%= f.text_field :number_auto %></div>

    <div class="bg-light border ms-auto-3"><%= f.label :brand_auto, 'Бренд а/м' %><br><%= f.select :brand_auto, ["AUDI", "ACURA", "BMW", "BYD", "CHEVROLET", "CHERY", "CITROEN", "CHANGAN", "CHRYSLER", "DAEWOO", "DODGE", "DAIHATSU", "DATSUN", "DONGFENG", "FORD", "FIAT", "FAW", "FOTON", "INFINITI", "ISUZU", "JAC", "GEELY", "GENESIS", "GREATWALL", "GAC", "HAVAL", "HONDA", "HYUNDAI", "HAIMA", "KIA", "LEXUS", "LIFAN", "MAZDA", "MINI", "MITSUBISHI", "MERCEDESBENZ",  "NISSAN", "OPEL", "PEUGEOT", "RAVON", "RENAULT", "ROVER", "SEAT", "SKODA",  "SSANGYONG", "SUZUKI", "SUBARU", "SMART", "TOYOTA", "VOLKSWAGEN", "VOLVO", "UAZ", "VAZ", "ZAZ", "GAZ"] %></div>

    <div class="bg-light border text-center ms-auto-3"><%= f.label :model_auto, 'Модель а/м' %><br><%= f.text_field :model_auto %></div>

    <div class="bg-light border text-center ms-auto-3"><%= f.label :km, 'Пробег в км' %><br><%= f.text_field :km %></div>

    <div class="bg-light border text-center ms-auto-3"><%= f.label :vin, 'Вин номер' %><br><%= f.text_field :vin %></div>

  </div>

  <div class="hstack gap-3">

    <div class="bg-light border text-center ms-5"><%= f.label :problem_user, 'Жалобы клиента на работу а/м, результат диагностики'%><br><%= f.text_area :problem_user, size: "52x10" %></div>

    <div class="bg-light border text-center ms-auto-3"><%= f.label :repair_user, 'Проделанная работа и пр.' %><br><%= f.text_area :repair_user, size: "52x10" %></div>

  </div>

  <div class="hstack gap-3" style="height: 100px;">

    <div class="bg-light border text-center ms-5"><%= f.label :swid, 'Тип блока, номер софта' %><br><%= f.text_field :swid %></div>

    <div class="bg-light border text-center ms-auto-3"><%= f.label :phone, 'Номер телефона' %><br><%= f.text_field :phone %></div>

    <div class="bg-light border text-center ms-auto-3"><%= f.label :price, 'Стоимость работ' %><br><%= f.text_field :price %></div>

    <div class="bg-light border text-center ms-auto-3"><%= f.label :data, 'Дата и время'%><%= f.datetime_local_field :data %></div>

  </div>

  <div class="hstack gap-3" style="height: 100px;">

    <div class="bg-info text-center ms-5 col-form-label-md"><%= f.label :submit, 'Записать' %><%= f.submit %></div>

    <%= link_to 'Показать все записи а/м', clients_path %>

  </div>

<% end %>

app/views/clients/search.html.erb
<h1>поиск клиента по номеру а/м</h1>

<form class="d-flex row-cols-md-6" role="search" >
  <input class="form-control ms-2" type="search" placeholder="Поиск" aria-label="Поиск">
  <button class="btn btn-outline-danger" type="submit">Поиск</button>
</form>

app/views/clients/show.html.erb
<h1>Вывод записаного клиента</h1>

    <tr>
      <p class="text-danger"> Гос номер а/м || <%= @client.number_auto %></p>
      <p class="text-dark">Бренд а/м || <%= @client.brand_auto %></p>
      <p class="text-dark"> Модель а/м || <%= @client.model_auto %></p>
      <p class="text-dark"> Пробег а/м || <%= @client.km %></p>
      <p class="text-dark"> Жалобы владельца а/м || <%= @client.problem_user %></p>
      <p class="text-dark"> Проделанные работы на а/м || <%= @client.repair_user %></p>
      <p class="text-dark"> Вин номер а/м || <%= @client.vin %></p>
      <p class="text-dark"> Тип блока и версия софта эбу || <%= @client.swid %></p>
      <p class="text-dark"> Телефон владельца а/м || <%= @client.phone %></p>
      <p class="text-dark"> Стоимость услуг || <%= @client.price %></p>
      <p class="text-dark"> Дата и время обращения || <%= @client.data %></p>
    </tr>