config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :clients do
    resources :problem_user
  end

  get '/' => 'home#index' # Метод вызывает открытия главную страницу без папок
  get '/contact' => 'pages#contact'  # Метод открывает контакты и адрес автосервиса из папки static_pages
  get 'home/index'



  # resource это такой метод который делает маршрут по Path (патерну) Рест (REST) и в Патерне Рест так определено
  # что НЬЮ получает GET  Крейт получает POST
  get 'contacts' => 'contacts#new' # Можно заменить на resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resource :contacts, only: [:create]
  resources :articles do
    resources :comments
  end
  # а дальше идет хешь,  ONLY это ключ хеша, а значение этого Хеша Массив С символами :new, :create методов
  # которые хотим использовать :new, :create
  get 'search' => 'clients#search'
  get 'clients' => 'clients#index' # Методо возвращает форму заполнения после ее ввода

  resources :clients
  resources :clients do
    resources :models
  end

  get 'articles' => 'articles#new'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

 get 'brands' => 'brands#index'
  resources :brands do
    resources :models
  end
  resources :brands

end

app/models/brand.rb
class Brand < ApplicationRecord

  has_many :models, dependent: :destroy

  validates :name, presence: true
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def new
  end

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      render action: 'new' #  если использовать Редирект - то  вывод представления из create  отображатьсяя не будет
      # будет делаться редирект на роутер SHOW - файл Креате можно удалить с редиректом он не используется
    else
      render action: 'new'
    end
  end

  def edit
    @brand = Brand.find(params[:id]) # Для того что бы отредактировать , нужно получить Сущьность (переменная обьект)
    # И передать ей все ее свойства, только после этого сущьность можно изменить. Представление edit.html.erb
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      redirect_to @brand  #  если использовать Редирект - то  вывод представления из create  отображатьсяя не будет
      # будет делаться редирект на роутер SHOW - файл Креате можно удалить с редиректом он не используется
    else
      render action: 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    redirect_to brands_path
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/edit.html.erb
<h1>Редактирование Бренда</h1>

<!- обязательно добaвлять  data: { turbo: false } - так как изменились Релься, -->
<!- иначе не будет отображаться результат на странице -->

  <%= form_for :brand, data: { turbo: false }, url: brand_path(@brand), method: :put do |f| %>

  <p>
    <%= f.label :name, 'Введите название бренда' %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit 'Сохранить' %>
  </p>

<% end %>

app/views/brands/index.html.erb
<h2>Список Брендов</h2>
<body>

  <% @brands.each do |brand| %>

  <table class="table table-bordered border-primary">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Бранд</th>
      <th scope="col"><%= button_to "Удалить Бранд", brand_path(brand), method: :delete %></th>
    </tr>
    </thead>

    <tbody class="table-group-divider" class="align-top">
    <tr>
      <th scope="row">1</th>
      <td><p class="text-danger"><%= brand.name %></p></td>
        <td>
          <%= link_to  "Добавить Модель для Бренда", brand_path(brand), method: :get %> |
          <%= link_to  "Редактировать Бренд", edit_brand_path(brand), method: :get %>
        </td>
    </tr>
  </table>
<% end %>
</body>








app/views/brands/new.html.erb
<h3>Введите Новый Бренд</h3>

<!- обязательно добaвлять  data: { turbo: false } - так как изменились Релься, -->
<!- иначе не будет отображаться результат на странице -->

<%= form_for :brand, data: { turbo: false }, url: brands_path do |f| %>

 <!-  вывод сообщения об ошибке -->
  <% if @brand && @brand.errors.any? %>
    <p>
      <ul>
        <%= @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

  <p>
    <%= f.label :name, 'Название Бренда' %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit 'Сохранить' %>
  </p>

<% end %>

app/views/brands/show.html.erb
<h4>Бренд для которого вы будете добавлять модель а/м</h4>
<body class="Secondary" >

<h2>
  <p class="text-success" ><%= @brand.name %></p>
</h2>

<p class="text-grey"> Уже записаны следующие модели для Бренда <%= @brand.name %></p>

<% @brand.models.each do |model| %>
<p>
  <i class="text-danger"><%= model.name %></i><br />
</p>
<% end %>

<h4>Добавьте для этого бренда модель а/м принадлежащую бренду</h4>
<p>
  <%= form_for([@brand, @brand.models.build]) do |f| %>

  <p class="text-danger" ><%= f.label :name, 'Модель а/м (Марка)' %><br />
  <p class="text-success" ><%= f.text_field :name %><br />
</p>

  <p>
    <%= f.submit 'Сохранить' %>
  </p>
</body>

<% end %>